
title: 金泽昊的主页 | 学术
page-top-title: 金泽昊 (Zehao Jin)
home-subtitle: 金泽昊&ensp;|&ensp;Zehao Jin
news-subtitle: '<i class="bi bi-newspaper"></i>&nbsp;新闻动态'
experience-subtitle: '<i class="bi bi-briefcase-fill"></i>&nbsp;实习经历'
publications-subtitle: '<i class="bi bi-file-text-fill"></i>&nbsp;学术发表'
awards-subtitle: '<i class="bi bi-award-fill"></i>&nbsp;荣誉奖项'
friends-subtitle: '<i class="bi bi-people-fill"></i>&nbsp;友情链接'
copyright-text: '&copy; 金泽昊 2026. All Rights Reserved.'
